### ISSUE TITLE
Publish 0.1.3 to clojars?

### ISSUE THREAD

**Issue by hden** [pedestal/pedestal.ions#4]
It's been awhile since the latest release (currently 0.1.0), maybe we can publish 0.1.3 to clojars?

https://clojars.org/io.pedestal/pedestal.ions

**Comment by ddeaguiar** [comment]
While I had published the initial release to Clojars, it's not really necessary. When you work with Datomic Ions, you're using tools.deps which supports git dependency coordinates. Thus, I stopped publishing the lib to Clojars and updated the README accordingly.
